name: Build and test Python package using a Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: sagemath/sagemath-develop
    steps:
      - uses: actions/checkout@v1
      - name: Test package
        run: |
          sage --version
          python3 setup.py test
