name: Build and test Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install sage from conda
      run: |
        conda env create -n sage environment.yml
        conda activate sage
    - name: Test package
      run: |
        python3 setup.py test
